### ISSUE TITLE
sz

### ISSUE THREAD

**Issue by sahilkumardev** [sahil4512/weather-app-js#1]

**Comment by SahilKumarDev** [comment]
Please help me sir

**Comment by sahil4512** [comment]
hi,

I also want to keep that for my profile repo i just didn’t got the time to
create it. you choose a different variant of it.

thanks

**Comment by SahilKumarDev** [comment]
can you help me because i have to create this name repo..
If you can rename it than thank you otherwise you cannot also unavailable to create a reopo of this name 

thanks

**Comment by sahilkumardev** [comment]
sc
